Add Count class for row counting with test and new PredicateSelection…
dmfs/ContentPal pull request #104
Opened 2017-10-02 17:52 UTC by lemonboston

…Matcher. Update jems to 1.9. #101

2017-10-02 21:13 UTC, dmfs commented on contentpal/src/main/java/org/dmfs/android/contentpal/tools/Count.java
> +            cursor.close();
`cursor.close()` should go into `finally`. Also make sure you have a unit test which covers this case (i.e. throw an exception in `mView.rows(…)` or `cursor.getCount()`).

2017-10-02 21:33 UTC, dmfs requested changes

2017-10-02 21:33 UTC, dmfs commented on contentpal/src/test/java/org/dmfs/android/contentpal/tools/CountTest.java
> +        doNothing().when(mockCursor).close();
This is probably one of the rare cases in which we actually should use `verify` to ensure `close()` is always called on the cursor. Unless you have a better idea to check that.

2017-10-02 21:33 UTC, dmfs commented on contentpal/src/main/java/org/dmfs/android/contentpal/tools/Count.java
> +            Cursor cursor = mView.rows(EmptyUriParams.INSTANCE, mPredicate, Absent.<String>absent());
I'm not sure if it makes a big difference, but maybe rebase and use the `withProjection` method to remove any projection (use `BaseColumns._ID` as the only projection value).
Also, please rename this class to `RowCount` as there is another more efficient way to get the row count which can be used for Content Providers which are backed by an SQL table. I'll create a separate issue for that.

2017-10-03 12:38 UTC, lemonboston commented
Made all the changes as suggested, ready for review again.

2017-10-03 13:34 UTC, dmfs approved these changes

2017-10-03 13:34 UTC, merged